"""Regenerate every data table and figure of paper-missingness-assumptions from the committed
pre-registered results. Nothing here is typed by hand: every number in the paper is read from
../../paper-plco-hypergraph/results/."""
import glob, pathlib, numpy as np, pandas as pd
SRC = pathlib.Path(__file__).resolve().parents[1]
OUT = pathlib.Path(__file__).resolve().parents[1] / "tables"
NAME = {"cand_eicu_regime": "eICU regimes", "cand_mimic4_regime": "MIMIC-IV regimes", "cand_nhanes": "NHANES mortality",
        "sweep_42739": "road safety", "cand_acs_income": "ACS income", "cand_airbnb": "Airbnb listings",
        "cand_higgs": "ATLAS Higgs", "cand_porto": "Porto Seguro"}
def nm(d): return NAME.get(d, d.replace("sweep_", "OpenML "))
def esc(s): return s.replace("_", "\\_")
def load(sub):
    fs = sorted(glob.glob(str(SRC / f"results/{sub}/*.csv"))); return pd.concat([pd.read_csv(f) for f in fs], ignore_index=True)
def panels(sub):
    x = load(sub); m = x[x.kind == "auroc"].groupby(["dataset", "model"]).value.mean().unstack("model")
    lk = {int(c.split("_")[1]): c for c in m.columns if c.startswith("lca_")}
    m["lca20"] = m[[lk[k] for k in sorted(lk) if k <= 20]].max(axis=1)
    m["K"] = [min([k for k in sorted(lk) if m.loc[d, lk[k]] >= 0.95 * m.loc[d, "panels_tree"]] or [np.inf]) for d in m.index]
    return m, x

def t_audit():
    dv, x = panels("rrstruct"); mi, _ = panels("rrmirror"); npan = x.groupby("dataset").n_panels.first()
    with open(OUT / "audit.tex", "w") as f:
        f.write("% generated by figures/make_tables.py -- do not edit\n\\begin{tabular}{lrrrrrr}\n\\toprule\n")
        f.write("Dataset & Panels & Tree & Pairwise & Mixture & $K$ & Mirror \\\\\n\\midrule\n")
        for d in dv.sort_values("panels_tree", ascending=False).index:
            f.write(f"{esc(nm(d))} & {int(npan[d])} & {dv.loc[d,'panels_tree']:.3f} & {dv.loc[d,'panels_l1']:.3f} & "
                    f"{dv.loc[d,'lca20']:.3f} & {int(dv.loc[d,'K'])} & {mi.loc[d,'panels_tree']:.3f} \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n")
    s = x[x.kind == "sites_purity"].groupby("dataset").value.max(); a = x[x.kind == "sites"].groupby("dataset").value.max()
    return dv, npan, {k: (float(s.get(k, np.nan)), float(a.get(k, np.nan))) for k in ("cand_eicu_regime", "cand_mimic4_regime")}

def t_negative():
    p = load("plasmode"); m = p[p.selfmask == 0]
    w = m.pivot_table(index=["gamma", "alignment"], columns="arm", values="excess")
    order = ["td_pc", "mvpc", "fci", "cdnod_true", "cdnod_est"]; lab = {"td_pc": "PC, test-wise deletion", "mvpc": "MVPC",
             "fci": "FCI", "cdnod_true": "CD-NOD, true regime", "cdnod_est": "CD-NOD, estimated regime"}
    with open(OUT / "negative.tex", "w") as f:
        f.write("% generated by figures/make_tables.py -- do not edit\n\\begin{tabular}{l" + "r" * 6 + "}\n\\toprule\n")
        f.write("& \\multicolumn{2}{c}{$\\gamma=0$} & \\multicolumn{2}{c}{$\\gamma=1$} & \\multicolumn{2}{c}{$\\gamma=2$} \\\\\n")
        f.write("\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}\nAlgorithm & aligned & control & aligned & control & aligned & control \\\\\n\\midrule\n")
        for arm in order:
            cells = " & ".join(f"{w.loc[(g, al), arm]:.2f}" for g in (0.0, 1.0, 2.0) for al in ("aligned", "closed"))
            f.write(f"{lab[arm]} & {cells} \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n")
    gap = (w.xs("aligned", level="alignment") - w.xs("closed", level="alignment"))
    return float(gap.loc[1.0, "td_pc"]), w

def t_detection():
    # results/misdiag: fresh seeds 20-39 under the pinned causal-learn 0.1.4.7. The earlier
    # results/mvpcdet run used 0.1.4.8, which carried a one-line regression (see ../MVPC-SPEC-VS-CODE.md).
    d = load("misdiag"); m = d[d.selfmask == 0]
    g = m.groupby(["gamma", "alignment"]).agg(inst=("n_indicators_with_parent", "mean"), pairs=("n_parent_pairs", "mean"), sti=("standin", "mean"))
    with open(OUT / "detection.tex", "w") as f:
        f.write("% generated by figures/make_tables.py -- do not edit\n\\begin{tabular}{llrrr}\n\\toprule\n")
        f.write("$\\gamma$ & Mask & Indicators with a parent & Parent pairs & Our stand-in \\\\\n\\midrule\n")
        for (gm, al), r in g.iterrows():
            f.write(f"{gm:.0f} & {'aligned' if al=='aligned' else 'control'} & {r.inst:.2f} & {r.pairs:.2f} & {r.sti:.2f} \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n")
    return g

def f_dissociation():
    """The paper's two results side by side: the diagnostic is fooled, structure learning is not.

    Emitted as pgfplots rather than as a raster or a matplotlib PDF, so the figure carries the
    document's own fonts and needs no plotting library to rebuild. Panel A is the confirmed
    positive (misdiag), panel B the pre-registered negative (plasmode). The error bars in A are the
    standard error over the twenty replicate seeds, so a reader can see that the null in B is a
    null measured with the precision to be one, and not a noisy nothing.
    """
    d = load("misdiag"); d = d[d.selfmask == 0]
    pl = load("plasmode"); pl = pl[pl.selfmask == 0]
    g = d.groupby(["gamma", "alignment"]).n_indicators_with_parent.agg(["mean", "sem"])

    def pts(rows, err):
        return " ".join((f"({x:.0f},{m:.3f}) +- (0,{e:.3f})" if err else f"({x:.0f},{m:.3f})")
                        for x, m, e in rows)

    L = [r"% generated by figures/make_tables.py -- do not edit",
         r"\begin{tikzpicture}",
         r"\begin{axis}[name=A, width=0.40\textwidth, height=4.6cm, xlabel={regime strength $\gamma$},",
         r"  ylabel={indicators with a parent}, xtick={0,1,2}, xmin=-0.15, xmax=2.15, ymin=0, ymax=8,",
         r"  title={\textbf{A}\quad The diagnostic step},",
         r"  title style={font=\small, at={(0,1.02)}, anchor=south west}, label style={font=\small},",
         r"  tick label style={font=\small}, legend style={font=\scriptsize, draw=none, fill=none,",
         r"  at={(0.5,-0.38)}, anchor=north, legend columns=1}, axis lines=left,",
         r"  error bars/y dir=both, error bars/y explicit]"]
    for al, opt, lab in [("aligned", r"mark=*, thick, color=red!65!black", "aligned to the hospital"),
                         ("closed", r"mark=square*, thick, dashed, color=blue!60!black", "closed-missingness control")]:
        r = g.xs(al, level="alignment").sort_index()
        L.append(r"\addplot[" + opt + r"] coordinates {" +
                 pts([(x, v["mean"], v["sem"]) for x, v in r.iterrows()], True) + r"};")
        L.append(r"\addlegendentry{" + lab + r"}")
    L.append(r"\end{axis}")

    ARMS = [("td_pc", "PC, test-wise deletion"), ("mvpc", "MVPC"), ("fci", "FCI"),
            ("cdnod_true", "CD-NOD, true regime"), ("cdnod_est", "CD-NOD, estimated regime")]
    MARK = ["mark=*, color=black", "mark=square*, color=red!70!black", "mark=triangle*, color=blue!65!black",
            "mark=diamond*, color=teal!75!black", "mark=pentagon*, color=violet!70!black"]
    L += [r"\begin{axis}[name=B, at={($(A.east)+(2.6cm,0)$)}, anchor=west, width=0.40\textwidth,",
          r"  height=4.6cm, xlabel={regime strength $\gamma$},",
          r"  ylabel={excess error, aligned $-$ control}, xtick={0,1,2}, xmin=-0.15, xmax=2.15,",
          r"  title={\textbf{B}\quad Structure learning},",
          r"  title style={font=\small, at={(0,1.02)}, anchor=south west}, label style={font=\small},",
          r"  tick label style={font=\small}, legend style={font=\scriptsize, draw=none, fill=none,",
          r"  at={(0.5,-0.38)}, anchor=north, legend columns=2}, axis lines=left,",
          r"  extra y ticks={0}, extra y tick labels={}, extra y tick style={grid=major, grid style={gray!45}}]"]
    for i, (arm, lab) in enumerate(ARMS):
        w = pl[pl.arm == arm].groupby(["gamma", "alignment"]).excess.mean().unstack("alignment")
        gap = (w["aligned"] - w["closed"]).sort_index()
        L.append(r"\addplot[" + MARK[i] + r", mark size=1.6pt, thin] coordinates {" +
                 pts([(x, v, 0) for x, v in gap.items()], False) + r"};")
        L.append(r"\addlegendentry{" + lab + r"}")
    L += [r"\end{axis}", r"\end{tikzpicture}"]
    out = pathlib.Path(__file__).resolve().parents[1] / "tables" / "fig_dissociation.tex"
    out.write_text("\n".join(L) + "\n")
    print(f"  {out.name} written")
    return g


def t_smgrid():
    """SMGRID2 (../paper-plco-hypergraph/prereg/SMGRID2.md): self-masking strength crossed with regime
    strength, self-masking applied to six of twelve columns so the regime is isolated on the other six.
    Returns the pooled aligned-minus-control gap per gamma with its standard error, the per-cell gap at
    gamma=1, the positive control, and the slope of the gap on s at gamma=1."""
    fs = sorted(glob.glob(str(SRC / "results/smgrid2/*.csv")))
    if not fs: return None
    d = pd.concat([pd.read_csv(f) for f in fs], ignore_index=True)
    w = d.pivot_table(index=["rep", "gamma", "selfmask_rate"], columns="alignment",
                      values="n_detect_clean").reset_index()
    w["gap"] = w["aligned"] - w["closed"]
    pooled = {g: (w[w.gamma == g].gap.mean(), w[w.gamma == g].gap.sem()) for g in (0.0, 1.0, 2.0)}
    cell1 = w[w.gamma == 1.0].groupby("selfmask_rate").gap.mean()
    ctrl = d[d.alignment == "closed"].groupby("selfmask_rate").n_detect_sm.mean()
    slope = float(np.polyfit(w[w.gamma == 1.0].selfmask_rate, w[w.gamma == 1.0].gap, 1)[0])
    return dict(pooled=pooled, cell1=cell1, ctrl=ctrl, slope=slope, nrep=int(w.rep.nunique()))


def t_graphscale():
    """GRAPHSCALE (../paper-plco-hypergraph/prereg/GRAPHSCALE.md): the same null at p = 12, 20, 30 and
    at a higher edge density. Returns the largest absolute aligned-minus-control difference over every
    arm, gamma and configuration, and the complete-data error at each setting."""
    fs = sorted(glob.glob(str(SRC / "results/graphscale/*.csv")))
    if not fs: return None
    d = pd.concat([pd.read_csv(f) for f in fs], ignore_index=True)
    w = d.pivot_table(index=["p", "density", "gamma", "arm"], columns="alignment",
                      values="excess").reset_index()
    w["diff"] = w["aligned"] - w["closed"]
    hard = d.groupby(["p", "density"]).shd_complete.mean()
    return dict(worst=float(w["diff"].abs().max()), hard=hard,
                nrep=int(d.groupby(["p", "density"]).rep.nunique().min()),
                ps=sorted(d.p.unique()))


def t_miscost():
    """MISCOST (../paper-plco-hypergraph/prereg/MISCOST.md): is the correlation matrix a
    constraint-based algorithm reads actually distorted by the regime? Returns the per-pair signed
    error averaged over replicates, for pairwise-complete correlation, plus the design's resolution."""
    fs = sorted(glob.glob(str(SRC / "results/miscost/*.csv")))
    if not fs: return None
    d = pd.concat([pd.read_csv(f) for f in fs], ignore_index=True)
    pp = d.groupby(["estimator", "alignment", "gamma", "pair"]).signed_err.mean().reset_index()
    a = pp[(pp.estimator == "available") & (pp.alignment == "aligned")]
    return dict(nrep=int(d.rep.nunique()),
                maxmean=float(a.groupby("gamma").signed_err.mean().abs().max()),
                maxrms=float(a.groupby("gamma").signed_err.apply(lambda x: np.sqrt(np.mean(x ** 2))).max()),
                res=0.0124 / np.sqrt(d.rep.nunique()))


def t_corrtrace():
    """CORRTRACE (../paper-plco-hypergraph/prereg/CORRTRACE.md): the median absolute correlation
    between an indicator and a value, pooled over hospitals and computed inside each hospital.
    Replicated, because one draw of this quantity is noisy enough to mislead: across replicates the
    pooled figure at a fixed regime spans more than a factor of two."""
    fs = sorted(glob.glob(str(SRC / "results/corrtrace/*.csv")))
    if not fs: return None
    d = pd.concat([pd.read_csv(f) for f in fs], ignore_index=True)
    med = d.groupby(["scope", "gamma"]).median_abs_corr.median()
    return dict(nrep=int(d.rep.nunique()),
                pooled={g: float(med[("pooled", g)]) for g in (0.0, 1.0, 2.0)},
                within=float(med[("within_hospital", 0.0)]))


def counts():
    dv, npan, site = t_audit(); gap, w = t_negative(); g = t_detection()
    sg = t_smgrid(); gs = t_graphscale(); ct = t_corrtrace(); mc = t_miscost()
    n = len(dv); mix = int((dv.lca20 >= 0.95 * dv.panels_tree).sum()); k10 = int((dv.K <= 10).sum())
    pair = int((dv.panels_l1 >= 0.98 * dv.panels_tree).sum()); hi = dv.panels_tree.max()
    with open(OUT / "counts.tex", "w") as f:
        f.write("% generated by figures/make_tables.py -- do not edit\n")
        for k, v in [("NData", n), ("MixMatch", mix), ("KTen", k10), ("PairMatch", pair),
                     ("EicuPanels", int(npan["cand_eicu_regime"])), ("EicuDep", f"{dv.loc['cand_eicu_regime','panels_tree']:.3f}"),
                     ("MimicDep", f"{dv.loc['cand_mimic4_regime','panels_tree']:.3f}"),
                     ("EicuPurity", f"{site['cand_eicu_regime'][0]:.2f}"), ("EicuAmi", f"{site['cand_eicu_regime'][1]:.3f}"),
                     ("MimicPurity", f"{site['cand_mimic4_regime'][0]:.2f}"), ("StructGap", f"{gap:+.2f}"),
                     ("DetAligned", f"{g.loc[(1.0,'aligned'),'inst']:.2f}"), ("DetControl", f"{g.loc[(1.0,'closed'),'inst']:.2f}"),
                     ("StandinAligned", f"{g.loc[(1.0,'aligned'),'sti']:.2f}"),
                     ("StandinControl", f"{g.loc[(1.0,'closed'),'sti']:.2f}")] + ([] if sg is None else [
                     # SMGRID2: the regime isolated from a genuine self-masking signal
                     ("SgReps", sg["nrep"]),
                     ("SgOne", f"{sg['pooled'][1.0][0]:.2f}"), ("SgOneLo", f"{sg['pooled'][1.0][0]-1.96*sg['pooled'][1.0][1]:.2f}"),
                     ("SgOneHi", f"{sg['pooled'][1.0][0]+1.96*sg['pooled'][1.0][1]:.2f}"),
                     ("SgZero", f"{sg['pooled'][0.0][0]:.2f}"), ("SgZeroLo", f"{sg['pooled'][0.0][0]-1.96*sg['pooled'][0.0][1]:.2f}"),
                     ("SgZeroHi", f"{sg['pooled'][0.0][0]+1.96*sg['pooled'][0.0][1]:.2f}"),
                     ("SgTwo", f"{sg['pooled'][2.0][0]:.2f}"),
                     ("SgHiRate", f"{sg['cell1'].iloc[-1]:.2f}"), ("SgLoRate", f"{sg['cell1'].iloc[0]:.2f}"),
                     ("SgSlope", f"{sg['slope']:+.3f}"),
                     ("SgCtrlLo", f"{sg['ctrl'].iloc[0]:.2f}"), ("SgCtrlHi", f"{sg['ctrl'].iloc[-1]:.2f}")]) + (
                     [] if gs is None else [
                     # GRAPHSCALE: the same null at larger p and higher density
                     ("GsWorst", f"{gs['worst']:.1f}"), ("GsReps", gs["nrep"]),
                     ("GsPmax", int(max(gs["ps"]))),
                     ("GsHardLo", f"{gs['hard'].loc[(20, 1.5)]:.1f}"), ("GsHardHi", f"{gs['hard'].loc[(20, 2.5)]:.1f}"),
                     ("GsHardTwelve", f"{gs['hard'].loc[(12, 1.5)]:.1f}"),
                     ("GsHardThirty", f"{gs['hard'].loc[(30, 1.5)]:.1f}")]) + ([] if mc is None else [
                     # MISCOST: the sufficient statistic is undistorted
                     ("McReps", mc["nrep"]), ("McMean", f"{mc['maxmean']:.4f}"),
                     ("McRms", f"{mc['maxrms']:.4f}"), ("McRes", f"{mc['res']:.4f}")]) + ([] if ct is None else [
                     # CORRTRACE: the marginal indicator-value association the regime induces
                     ("CtReps", ct["nrep"]), ("CtPoolZero", f"{ct['pooled'][0.0]:.3f}"),
                     ("CtPoolOne", f"{ct['pooled'][1.0]:.3f}"), ("CtPoolTwo", f"{ct['pooled'][2.0]:.3f}"),
                     ("CtWithin", f"{ct['within']:.3f}")]):
            f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
    f_dissociation()
    print(f"audit.tex, negative.tex, detection.tex, counts.tex written")
    print(f"  {n} datasets; mixture matches {mix}, K<=10 on {k10}, pairwise matches {pair}; max dependence {hi:.3f}")
    print(f"  eICU purity {site['cand_eicu_regime'][0]:.2f} AMI {site['cand_eicu_regime'][1]:.3f}; structural gap at gamma 1 {gap:+.2f}")
    print(f"  detection aligned {g.loc[(1.0,'aligned'),'inst']:.2f} vs control {g.loc[(1.0,'closed'),'inst']:.2f}; stand-in {g.loc[(1.0,'aligned'),'sti']:.2f} vs {g.loc[(1.0,'closed'),'sti']:.2f}")
if __name__ == "__main__": counts()
