"""Regenerate every table, figure and number of the merged paper from the committed results.

The two drafts this paper merges each had their own generator. Rather than copy their code into a
third file, which would let the two diverge, both are kept verbatim as `gen_regimes.py` and
`gen_assumptions.py` and driven from here. Each writes its own fragments into ../tables and its own
`counts.tex`; we run them in turn, keep both macro sets, and write the union once.

`NData` is dropped: it is the same seventeen datasets as `NDatasets`, and the merged prose uses the
latter everywhere.

Run from the paper directory: ../paper-plco-hypergraph/.venv/bin/python figures/make_tables.py
"""
import importlib.util, pathlib, re, sys

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parents[0] / "tables"


def run(modname):
    spec = importlib.util.spec_from_file_location(modname, HERE / f"{modname}.py")
    m = importlib.util.module_from_spec(spec); sys.modules[modname] = m
    sys.path.insert(0, str(HERE))
    spec.loader.exec_module(m)
    m.counts()
    txt = (OUT / "counts.tex").read_text()
    return dict(re.findall(r'\\newcommand\{\\(\w+)\}\{([^}]*)\}', txt))


def main():
    print("--- regimes half"); a = run("gen_regimes")
    print("--- assumptions half"); b = run("gen_assumptions")
    merged = dict(a)
    for k, v in b.items():
        if k == "NData": continue
        if k in merged and merged[k] != v:
            raise SystemExit(f"macro {k} disagrees between halves: {merged[k]!r} vs {v!r}")
        merged[k] = v
    with open(OUT / "counts.tex", "w") as f:
        f.write("% generated by figures/make_tables.py -- do not edit\n")
        for k in sorted(merged): f.write(f"\\newcommand{{\\{k}}}{{{merged[k]}}}\n")
    print(f"\ncounts.tex: {len(merged)} macros ({len(a)} from the regimes half, "
          f"{len(b) - 1} from the assumptions half, NData dropped)")


if __name__ == "__main__": main()
